"""systemd --user backend (Linux)."""

import os
from pathlib import Path
import re
import shlex
import subprocess

from .. import _proc
from ..errors import ManagerError
from .base import ServiceBackend

PROPERTIES = ("Id", "LoadState", "FragmentPath", "ExecStart", "ActiveState", "MainPID",
              "ControlPID", "NeedDaemonReload", "DropInPaths", "Transient", "Type")


class SystemdBackend(ServiceBackend):
    name = "systemd"

    def unit_name(self, logical):
        from . import systemd_unit

        return systemd_unit(logical)

    def definition_path(self, logical):
        return self.settings.service_dir / self.unit_name(logical)

    @staticmethod
    def quote(value):
        ServiceBackend._require_single_line(value)
        return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%").replace("$", "$$") + '"'

    def render(self, logical, description, args):
        return ("[Unit]\nDescription=" + description + "\n\n[Service]\nType=simple\nExecStart="
                + " ".join(self.quote(a) for a in args)
                + "\nRestart=on-failure\n\n[Install]\nWantedBy=default.target\n")

    def _link_command(self, path):
        return shlex.join([self.settings.systemctl, "--user", "link", str(path)])

    def verify(self, logical, args, text, *, verify_process=True):
        unit, path = self.unit_name(logical), self.definition_path(logical)
        link = self._link_command(path)
        try:
            if path.read_text() != text:
                raise ManagerError(f"service refused: {path} is not the unmodified unit generated by llms")
            result = self.runner([self.settings.systemctl, "--user", "show", unit,
                                  "--no-pager", "--all", "--property=" + ",".join(PROPERTIES)],
                                 capture_output=True, text=True, timeout=10)
            if result.returncode:
                raise ManagerError(f"cannot inspect user service: {result.stderr.strip()}")
            loaded = {}
            for line in result.stdout.splitlines():
                key, separator, value = line.partition("=")
                if not separator or key in loaded or key not in PROPERTIES:
                    raise ManagerError("service refused: malformed systemctl show response")
                loaded[key] = value
            if loaded.keys() != set(PROPERTIES):
                raise ManagerError("service refused: incomplete systemctl show response")
            if loaded["LoadState"] != "loaded" or not loaded["FragmentPath"]:
                raise ManagerError(f"unit is not discoverable by the user manager; for an external unit run {link}, then systemctl --user daemon-reload")
            if (loaded["Id"] != unit or not Path(loaded["FragmentPath"]).is_absolute()
                    or not self._same_file(loaded["FragmentPath"], path)):
                raise ManagerError("service refused: loaded FragmentPath/Id belongs to a different unit source")
            if (loaded["NeedDaemonReload"] != "no" or loaded["DropInPaths"]
                    or loaded["Transient"] != "no" or loaded["Type"] != "simple"):
                raise ManagerError("service refused: stale, overridden, transient, or unsupported unit; reconcile it explicitly")
            prefix = f"{{ path={args[0]} ; argv[]={' '.join(args)} ; ignore_errors=no ; "
            metadata = r"start_time=\[[^\]\n]*\] ; stop_time=\[[^\]\n]*\] ; pid=\d+ ; code=[^;{}\n]* ; status=[^;{}\n]* }"
            if not re.fullmatch(re.escape(prefix) + metadata, loaded["ExecStart"]):
                raise ManagerError("service refused: loaded ExecStart does not match generated command")
            state, pid = loaded["ActiveState"], loaded["MainPID"]
            if state not in ("active", "inactive", "failed") or not pid.isdecimal() or loaded["ControlPID"] != "0":
                raise ManagerError("service refused: unstable or unknown process state")
            if state == "active":
                if int(pid) <= 0:
                    raise ManagerError("service refused: active unit has no verifiable main process")
                if verify_process:
                    verify_live_process(int(pid), args)
            elif pid != "0":
                raise ManagerError("service refused: inactive unit still has a main process")
            return state == "active"
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise ManagerError(f"cannot verify installed/live service binding: {exc}; install the unit first and link external units with {link}") from exc

    def act(self, action, logicals, *, prefix=""):
        units = [self.unit_name(name) for name in logicals]
        result = self.runner([self.settings.systemctl, "--user", action, *units], capture_output=True, text=True)
        if result.returncode:
            raise ManagerError(f"{prefix}{action} failed: {result.stderr.strip()}")

    def standard_dir(self):
        home = Path(os.environ.get("HOME", str(Path.home())))
        return Path(os.environ.get("XDG_CONFIG_HOME", str(home / ".config"))) / "systemd" / "user"

    def activation_hint(self, paths):
        lines = []
        standard = self.standard_dir().expanduser().absolute().resolve()
        for path in paths:
            if Path(path).parent.resolve() != standard:
                lines.append("The unit is outside the standard user unit directory; link it explicitly:")
                lines.append(self._link_command(path))
        lines.append("Then reload explicitly:")
        lines.append(shlex.join([self.settings.systemctl, "--user", "daemon-reload"]))
        return lines

    def logs_command(self, logical, *, follow=False, lines=200):
        command = ["journalctl", "--user", "-u", self.unit_name(logical), "-n", str(lines), "--no-pager"]
        return command + (["-f"] if follow else [])


def verify_live_process(pid, args):
    """Raise unless the live process runs exactly args (argv and executable)."""
    if (_proc.argv(pid) != [str(a) for a in args]
            or Path(_proc.exe(pid)).resolve(strict=True) != Path(args[0]).resolve(strict=True)):
        raise ManagerError("service refused: live process binding differs from generated command")
